---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springci/spring-boot-ci-image
    tag: master
inputs:
- name: git-repo
- name: distribution-repository
caches:
- path: maven
- path: gradle
run:
  path: spring-boot/ci/scripts/build-integration-tests.sh
