resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: springio/artifactory-resource
    tag: 0.0.1-SNAPSHOT
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/philwebb/spring-boot.git
    username: ((github-username))
    password: ((github-password))
    branch: maven-restruct
    ignore_paths: ["ci/images/*"]
- name: ci-images-git-repo
  type: git
  source:
    uri: https://github.com/philwebb/spring-boot.git
    branch: maven-restruct
    paths: ["ci/images/*"]
- name: spring-boot-ci-image
  type: docker-image
  source:
    repository: springci/spring-boot-ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: master
- name: artifactory-repo
  type: artifactory-resource
  source:
    uri: http://repo.example.com
    username: ((artifactory-username))
    password: ((artifactory-password))
    build_name: "Spring Boot - 2.0.x"
jobs:
- name: build-spring-boot-ci-image
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: spring-boot-ci-image
    params:
      build: ci-images-git-repo/ci/images/spring-boot-ci-image
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: build-project
    file: git-repo/ci/tasks/build-project.yml
  - aggregate:
    - task: build-sample-tests
      file: git-repo/ci/tasks/build-sample-tests.yml
    - task: build-integration-tests
      file: git-repo/ci/tasks/build-integration-tests.yml
    - task: build-deployment-tests
      file: git-repo/ci/tasks/build-deployment-tests.yml
  - put: artifactory
    params:
      repo: libs-snapshot-local
      build_number: "${BUILD_ID}"
      folder: distribution-repository
      build_url: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}"
      build_number: "${BUILD_NAME}"
      artifact-set:
      - include:
        - "**/spring-boot-docs-*.zip"
      properties:
        zip-type: docs
        zip-deployed: false
groups:
- name: "Spring Boot"
  jobs:
  - build
- name: "CI Images"
  jobs:
  - build-spring-boot-ci-image